name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t prayushbogati1/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true prayushbogati1/react-test npm test

      - run: docker build -t prayushbogati1/multi-client ./client
      - run: docker build -t prayushbogati1/multi-nginx ./nginx
      - run: docker build -t prayushbogati1/multi-server ./server
      - run: docker build -t prayushbogati1/multi-worker ./worker

      - run: docker push prayushbogati1/multi-client
      - run: docker push prayushbogati1/multi-nginx
      - run: docker push prayushbogati1/multi-server
      - run: docker push prayushbogati1/multi-worker
